/* eslint-disable no-unused-vars */
export enum StateAction {
  SET_REPOSITORY_PATH = 'SET_REPOSITORY_PATH',
  SET_COMMITS = 'SET_COMMITS',
  SET_COMMIT = 'SET_COMMIT',
  SET_STATUS = 'SET_STATUS',
  SET_REMOTE_BRANCHES = 'SET_REMOTE_BRANCHES',
  SET_LOCAL_BRANCHES = 'SET_LOCAL_BRANCHES',
  SET_SNACKBAR = 'SET_SNACKBAR',
  RESET_APP_STATE = 'RESET_APP_STATE',
  SET_IS_MODAL_OPEN = 'SET_IS_MODAL_OPEN',
  INCREASE_MAX_COMMIT_LOAD = 'INCREASE_MAX_COMMIT_LOAD',
  SET_IS_LOAD_MORE_BUTTON_DISABLED = 'SET_IS_LOAD_MORE_BUTTON_DISABLED',
}
