export const CHANELS = {
  CLONE: 'clone',
  OPEN_FILE: 'open-file',
  IS_REPO: 'is-repo',
  FETCH_DIRECTORY_STATUS: 'fetch-directory-status',
  GET_COMMIT_DIFF: 'get-commit-diff',
  GET_REMOTES: 'get-remotes',
  GET_REMOTE_BRANCHES: 'get-remote-branches',
  ADD_REMOTE: 'add-remote',
  CREATE_BRANCH: 'create-branch',
  DELETE_BRANCH: 'delete-branch',
  COMMIT: 'commit',
  PUSH: 'push',
  PULL: 'pull',
  MERGE: 'merge',
} as const;
